config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'

  devise_for :admins
  resources :categories
  
  devise_for :users, controllers: {:sessions => 'users/sessions', 
  :registrations => 'users/registrations'}
  
  root 'static_pages#home'
  
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "admin", to: "devise/sessions#new"  #Route for admin login
    get "register", to: "users/registrations#new"
    get "update", to: "users/registrations#edit"
  end
  
  devise_scope :admin do
    get "admins/sign_out", to: "devise/sessions#destroy"
  end
  
  
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'after sign in path for' => 'static_pages#home'
  get 'after sign out path for' => 'static_pages#home'
  post 'cart' => 'cart#create'
  get 'cart' => 'cart#index'
  post 'cart/remove' => 'cart#removeCartItem'

  get 'checkout' => 'checkouts#new'
  get 'checkouts' => 'checkouts#index'
  post 'checkouts' => 'checkouts#create'
  get 'thankyou' => 'static_pages#thankyou'
  get 'orderhistory' => 'checkouts#index'
  
  resources :orders
  resources :basketitems
  resources :products
  resources :addresses
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Relationship user-address is 1-*
  has_many :addresses
  #Relationship user-order is 1-*
  has_many :orders
  has_many :checkouts
  
  #Validation of input when user is created
  #These fields cannot be blank and some have minimum/maximum lengths
  validates :first_name, presence: true, length:{maximum:50}
  
  validates :last_name, presence: true, length:{maximum:50}
  
  validates :email, presence: true, length:{minimum:5, maximum:255},
             uniqueness: true
             
  #Don't validate password because devise does this anyway and 
  #if we validate here we can't leave black on the update form
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
    before_filter :numberOfCartItems
    before_filter :calculateTotal
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_filter :numberOfCartItems
    before_filter :calculateTotal
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
    before_filter :numberOfCartItems
    before_filter :calculateTotal
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_filter :numberOfCartItems
    before_filter :calculateTotal
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

#  
#  before_filter :configure_permitted_parameters

#  protected

  # If you have extra params to permit, append them to the sanitizer.
  #Allows other fields to be used at sign_up
#  def configure_permitted_parameters
#    devise_parameter_sanitizer.for(:sign_up) do |u|
#      u.permit(:first_name, :last_name, :phone_number,
#        :email, :password, :password_confirmation)
#        .require(:first_name, :last_name,
#        :email, :password, :password_confirmation)
#    end
    
  # If you have extra params to permit, append them to the sanitizer.
#    devise_parameter_sanitizer.for(:account_update) do |u|
#      u.permit(:first_name, :last_name, phone_number,
#        :email, :password, :password_confirmation, :current_password)
#    end
#  end
end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    before_filter :numberOfCartItems
    before_filter :calculateTotal
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
    before_filter :numberOfCartItems
    before_filter :calculateTotal
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :numberOfCartItems
  before_filter :calculateTotal
  before_filter :setUpCategories
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :phone_number, :email)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <<!--First name field using bootstrap and devise-->
  <div class="form-group" class="field">
    <label for="RegisterFirstName" class="col-sm-2 control-label"><%= f.label :first_name %></label>
    <div class="col-sm-10"><input type="text" class="form-control" placeholder="First Name" 
    <%= f.text_field :first_name %></input></div>
  </div>
  <!--Last name field using bootstrap and devise-->
  <div class="form-group" class="field">
    <label for="RegisterLastName" class="col-sm-2 control-label"><%= f.label :last_name %></label>
    <div class="col-sm-10"><input type="text" class="form-control" placeholder="Last Name" 
    <%= f.text_field :last_name %></input></div>
  </div>
  <!--Phone number field using bootstrap and devise-->
  <div class="form-group" class="field">
    <label for="RegisterPhoneNumber" class="col-sm-2 control-label"><%= f.label :phone_number %></label>
    <div class="col-sm-10"><input type="text" class="form-control" placeholder="Phone Number" 
    <%= f.text_field :phone_number %></input></div>
  </div>
  <!--Email field using bootstrap and devise-->
  <div class="form-group" class="field">
    <label for="RegisterEmail" class="col-sm-2 control-label"><%= f.label :email %></label>
    <div class="col-sm-10"><input type="email" class="form-control" placeholder="Email" 
    <%= f.email_field :email, autofocus: true %> </input></div>
  </div>
  <!--Password field using bootstrap and devise-->
  <div class="form-group" class="field">
    <label for="RegisterPassword" class="col-sm-2 control-label"><%= f.label :password %></label>
    <div class="col-sm-10"><input type="password" class="form-control" 
    placeholder="<%if @minimum_password_length%><%=@minimum_password_length%> characters minimum
    <% end %>"
    <%= f.password_field :password, autocomplete: "off" %> </input></div>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!--Page provides the title Users to the title variable in the application.html.erb page-->
<%provide(:title, "Update Details")%>

<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!--Page provides the title Users to the title variable in the application.html.erb page-->
<%provide(:title, "Users")%>

<!--Comment out notice here because code in the application view will display it-->
<!--<p id="notice"><%#= notice %></p>-->

<h1>All Users:</h1>

<table class="table">
  <thead>
    <tr>
      <th>CustomerID</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', user, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%#= link_to 'New User', new_user_path %>-->

app/views/users/new.html.erb
<!--Page provides the title Users to the title variable in the application.html.erb page-->
<%provide(:title, "Register")%>

<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/show.html.erb
<!--Page provides the title Users to the title variable in the application.html.erb page-->
<%provide(:title, "Users")%>

<!--Comment out notice here because code in the application view will display it-->
<!--<p id="notice"><%#= notice %></p>-->

<dl class="dl-horizontal">

<p>
  <dt><strong>First name:</strong></dt>
  <dd><%= @user.first_name %></dd>
</p>

<p>
  <dt><strong>Last name:</strong></dt>
  <dd><%= @user.last_name %></dd>
</p>

<p>
  <dt><strong>Phone number:</strong></dt>
  <dd><%= @user.phone_number %></dd>
</p>

<p>
  <dt><strong>Email:</strong></dt>
  <dd><%= @user.email %></dd>
</p>
</dl>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>