config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'

  devise_for :admins
  resources :categories
  
  devise_for :users, controllers: {:sessions => 'users/sessions', 
  :registrations => 'users/registrations'}
  
  root 'static_pages#home'
  
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "admin", to: "devise/sessions#new"  #Route for admin login
    get "register", to: "users/registrations#new"
    get "update", to: "users/registrations#edit"
  end
  
  devise_scope :admin do
    get "admins/sign_out", to: "devise/sessions#destroy"
  end
  
  
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'after sign in path for' => 'static_pages#home'
  get 'after sign out path for' => 'static_pages#home'
  post 'cart' => 'cart#create'
  get 'cart' => 'cart#index'
  post 'cart/remove' => 'cart#removeCartItem'

  get 'checkout' => 'checkouts#new'
  get 'checkouts' => 'checkouts#index'
  post 'checkouts' => 'checkouts#create'
  get 'thankyou' => 'static_pages#thankyou'
  get 'orderhistory' => 'checkouts#index'
  
  resources :orders
  resources :basketitems
  resources :products
  resources :addresses
  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :product_categories

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :numberOfCartItems
  before_filter :calculateTotal
  before_filter :setUpCategories
  
  
  #Only allows admins to access these controller actions
  before_filter :authenticate_admin!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
  #filter by colour, range, price
  if params[:category]
   @products = Product.joins(:product_categories).where('product_categories.category_id' => params[:category]).paginate(:page => params[:page], :per_page => 6)
  elsif params[:a]
   @products = Product.where('products.price < 30').paginate(:page => params[:page], :per_page => 6)
  elsif params[:b]
   @products = Product.where('products.price < 50 AND products.price >= 30').paginate(:page => params[:page], :per_page => 6) 
  elsif params[:c]
   @products = Product.where('products.price < 70 AND products.price >= 50').paginate(:page => params[:page], :per_page => 6)
  elsif params[:d]
   @products = Product.where('products.price > 70').paginate(:page => params[:page], :per_page => 6) 
  else  
    @products = Product.all.paginate(:page => params[:page], :per_page => 6)
  end

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
  
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    #retrieve the preiously assigned product categories
    setUpProductCategories
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    
    isSaved = @product.save
    
    #populate product_category table upon product creation
    params['category'].each do | categoryId | 
      newProductCategories = ProductCategory.new(product_id: @product.id, category_id: categoryId)
      @isSaved2 = newProductCategories.save
    end

    respond_to do |format|
      if isSaved and @isSaved2
        format.html { redirect_to @product }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    
    ProductCategory.destroy_all(:product_id => params[:id])
    #reassign categories
    params['category'].each do | categoryId | 
      newProductCategories = ProductCategory.new(product_id: @product.id, category_id: categoryId)
      @isSaved2 = newProductCategories.save
    end
    
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url}
      format.json { head :no_content }
    end
  end

  def setUpProductCategories
  #retrieve previously assigned product categories
  @pcArray= ProductCategory.where(:product_id => params[:id])
  
  @categoryIds = []
  
  @pcArray.each do |pc|
    
    @categoryIds.push(pc.category_id)
    
    end
    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:description, :image, :stock_qty, :price, :title)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="container" style="width:90%">
		<h1>Product Information</h1>
		<form>
		  <div class="form-group row">
		      <%= f.label :title, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
		      <%= f.text_field :title, class:"form-control"%>
		    </div>
		  </div>
		  <div class="form-group row">
		      <%= f.label :description, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
		      <%= f.text_field :description, class:"form-control"%>
		    </div>
		  </div>
		  <div class="form-group row">
		      <%= f.label :image, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
		      <%= f.text_field :image, class:"form-control"%>
		    </div>
		  </div>
		  <div class="form-group row">
		      <%= f.label :stock_qty, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
		      <%= f.number_field :stock_qty, class:"form-control"%>
		    </div>
		  </div>
		  <div class="form-group row">
		      <%= f.label :price, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
		      <%= f.text_field :price, class:"form-control"%>
		    </div>
		  </div>
		  
		  <div class="form-group row">
		      <%= f.label :colour, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
            <script type="text/javascript">
               $(document).ready(function() {
               $('#example-without-maxHeight').multiselect();
               });
            </script>
            <select name="category[]" id="example-without-maxHeight" multiple="multiple">
               <% if @categoryIds !=nil %>
               		<% @colour.each do |colour| %>
               			<% if @categoryIds.include?(colour.id) %>
			   				<option value="<%= colour.id %>" selected><%= colour.name %></option>
			   			<% else %>
			   				<option value="<%= colour.id %>"><%= colour.name %></option>
			  			<% end %>
			  		<% end %>
			  <% else %>
			         <% @colour.each do |colour| %>
			   				<option value="<%= colour.id %>"><%= colour.name %></option>
			  		 <% end %>
			  <% end %>
            </select>
		    </div>
		  </div>
		  
		  <div class="form-group row">
		      <%= f.label :range, class:"col-sm-2 form-control-label"%>
		    <div class="col-sm-10">
            <script type="text/javascript">
               $(document).ready(function() {
               $('#example-with-maxHeight').multiselect({
               });
               });
            </script>
			<select name="category[]" id="example-with-maxHeight" multiple="multiple">
               <% if @categoryIds !=nil %>
               		<% @range.each do |range| %>
               			<% if @categoryIds.include?(range.id) %>
			   				<option value="<%= range.id %>" selected><%= range.name %></option>
			   			<% else %>
			   				<option value="<%= range.id %>"><%= range.name %></option>
			  			<% end %>
			  		<% end %>
			  <% else %>
			         <% @range.each do |range| %>
			   				<option value="<%= range.id %>"><%= range.name %></option>
			  		 <% end %>
			  <% end %>
            </select>		    
          </div>
		  </div>
		  
       	<div class="form-group row">
		    	<div class="col-sm-offset-2 col-sm-10">
		      	<%= f.submit "Submit Product Details", class:"btn btn-secondary" %>
		    	</div>
		  	</div>
		  	<div class="form-group row">
	      	<div class="col-sm-offset-2 col-sm-10">
		      	<%= link_to 'Back', products_path, class:"btn btn-secondary"%>
		    </div>
     </div> 
    </form>
	</div>
<% end %>

app/views/products/edit.html.erb
<!--Page provides the title Addresses to the title variable in the application.html.erb page-->
<%provide(:title, "Products")%>

<%= render 'form' %>

app/views/products/index.html.erb
<!--Page provides the title Addresses to the title variable in the application.html.erb page-->
<%provide(:title, "Products")%>

<p id="notice"><%= notice %></p>

<div class="container-fluid">
		  		<% if current_admin %>
				<%= link_to 'Add New Product', new_product_path, class: "btn btn-primary" %>
			<% end %>
			<p> </p>
	<div class="row">
    	<div class="col-sm-3 col-md-2 sidebar">
        	<ul class="nav nav-sidebar">
		 		<div class="panel-group" id="accordion">
  					<div class="panel panel-default">
    					<div class="panel-heading">
      						<h4 class="panel-title">
        						<a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Shop by Range</a>
      						</h4>
    					</div>
    					<div id="collapse1" class="panel-collapse collapse in">
      						<div class="panel-body">		      		
      							<% @range.each do |range| %>
      								<li><%= link_to range.name, products_path(:category => range.id) %></li>
		        				<% end %>
		        			</div>
    					</div>
  					</div>
  					<div class="panel panel-default">
    					<div class="panel-heading">
      						<h4 class="panel-title">
        						<a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Shop by Colour</a>
      						</h4>
    					</div>
    					<div id="collapse2" class="panel-collapse collapse">
      						<div class="panel-body">		      		
      							<% @colour.each do |colour| %>
      								<li><%= link_to colour.name, products_path(:category => colour.id) %><li>
		        				<% end %>
		        			</div>
    					</div>
  					</div>
  					<div class="panel panel-default">
    					<div class="panel-heading">
      						<h4 class="panel-title">
        						<a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Shop by Price</a>
      						</h4>
    					</div>
    					<div id="collapse3" class="panel-collapse collapse">
      						<div class="panel-body">
      							<li><%= link_to 'Under €30.00', products_path(:a => '<30') %></li>
      							<li><%= link_to '€30.00 - €50.00', products_path(:b => '30-50') %></li>
      							<li><%= link_to '€50.00 - €70.00', products_path(:c => '50-70') %></li>
      							<li><%= link_to '€70.00+', products_path(:d => 'over70') %></li>
      						</div>
    					</div>
  					</div>
				</div>
		 	</ul>
		</div>
  		<div class="row">
  			<% @products.each do |product| %>
	  			<div class="col-sm-6 col-md-3">
	    			<div class="thumbnail">
	    				<%= image_tag (product.image), :class => "img-responsive" %>
	      				<div class="caption">
	        				<h3><%= product.title %></h3>
	        				<p>€<%= product.price %></p>

	        				<% if current_admin %>
	        				<%= link_to 'Show', product, class:"btn btn-success" %>
        					<%= link_to 'Edit', edit_product_path(product), class:"btn btn-warning"  %>
	        				<%= link_to 'Destroy', product, method: :delete, class:"btn btn-danger",  data: { confirm: 'Are you sure?' } %>
	        				<% else %>
	        				<%= link_to 'Show', product, class:"btn btn-success" %>
	        				<p> </p>
	        				<%= button_to 'Add to Cart', cart_path(:id => product.id), class:"btn btn-primary" %>
	      					<% end %>
	      				</div>
	    			</div>
	    		</div>
	  		<% end %>
	  		<%= will_paginate @products %>
		</div>
	<br>
 </div>	
 
 		

app/views/products/new.html.erb
<!--Page provides the title Addresses to the title variable in the application.html.erb page-->
<%provide(:title, "Products")%>


<%= render 'form' %>

app/views/products/show.html.erb
<!--Page provides the title Addresses to the title variable in the application.html.erb page-->
<%provide(:title, "Products")%>

<p id="notice"><%= notice %></p>

	<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
        	<ul class="nav nav-sidebar">
		 		<div class="panel-group" id="accordion">
  					<div class="panel panel-default">
    					<div class="panel-heading">
      						<h4 class="panel-title">
        						<a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Shop by Range</a>
      						</h4>
    					</div>
    					<div id="collapse1" class="panel-collapse collapse in">
      						<div class="panel-body">		      		
      							<% @range.each do |range| %>
      								<li><%= link_to range.name, products_path(:category => range.id) %></li>
		        				<% end %>
		        			</div>
    					</div>
  					</div>
  					<div class="panel panel-default">
    					<div class="panel-heading">
      						<h4 class="panel-title">
        						<a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Shop by Colour</a>
      						</h4>
    					</div>
    					<div id="collapse2" class="panel-collapse collapse">
      						<div class="panel-body">		      		
      							<% @colour.each do |colour| %>
      								<li><%= link_to colour.name, products_path(:category => colour.id) %><li>
		        				<% end %>
		        			</div>
    					</div>
  					</div>
  					<div class="panel panel-default">
    					<div class="panel-heading">
      						<h4 class="panel-title">
        						<a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Shop by Price</a>
      						</h4>
    					</div>
    					<div id="collapse3" class="panel-collapse collapse">
      						<div class="panel-body">
      							<li><%= link_to 'Under €30.00', products_path(:a => '<30') %></li>
      							<li><%= link_to '€30.00 - €50.00', products_path(:b => '30-50') %></li>
      							<li><%= link_to '€50.00 - €70.00', products_path(:c => '50-70') %></li>
      							<li><%= link_to '€70.00+', products_path(:d => 'over70') %></li>
      						</div>
    					</div>
  					</div>
				</div>
		 	</ul>
		</div>
      <!-- Portfolio Item Row -->
      <div class="row">

          <div class="col-md-5">
              <%= image_tag (@product.image), :class => "img-responsive" %>
          </div>

          <div class="col-md-4">
		      <div class="caption">
		        <h3><%= @product.title %></h3>
		        <p><%= @product.description %></p>
		        <p>€<%= @product.price %></p>
		        <% if current_admin %>
		        <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-warning"  %>
	        	<%= link_to 'Destroy', @product, method: :delete, class:"btn btn-danger",  data: { confirm: 'Are you sure?' } %>
		        <% else %>
		        <%= button_to 'Add to Cart', cart_path(:id => @product.id), class:"btn btn-primary" %>
		        <% end %>
		      </div>
		      <div class="form-group row">
	      		<div class="col-sm-offset-2 col-sm-10">
		    		</div>
     			</div>
          </div>
      </div>
      <!-- /.row -->
	</div>