config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'

  devise_for :admins
  resources :categories
  
  devise_for :users, controllers: {:sessions => 'users/sessions', 
  :registrations => 'users/registrations'}
  
  root 'static_pages#home'
  
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "admin", to: "devise/sessions#new"  #Route for admin login
    get "register", to: "users/registrations#new"
    get "update", to: "users/registrations#edit"
  end
  
  devise_scope :admin do
    get "admins/sign_out", to: "devise/sessions#destroy"
  end
  
  
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'after sign in path for' => 'static_pages#home'
  get 'after sign out path for' => 'static_pages#home'
  post 'cart' => 'cart#create'
  get 'cart' => 'cart#index'
  post 'cart/remove' => 'cart#removeCartItem'

  get 'checkout' => 'checkouts#new'
  get 'checkouts' => 'checkouts#index'
  post 'checkouts' => 'checkouts#create'
  get 'thankyou' => 'static_pages#thankyou'
  get 'orderhistory' => 'checkouts#index'
  
  resources :orders
  resources :basketitems
  resources :products
  resources :addresses
  resources :users

end

app/views/layouts/_footer.html.erb
<!-- Add in html for footer here. This will be used on all pages. -->

app/views/layouts/_header.html.erb
<%= image_tag "logo/logo.png", :class => "img-responsive" %>

<% if !current_admin %>
<div align="right"><strong><%= @length %> Cart item(s)</strong></div>
<div align="right"><strong>My Cart Total: €<%= @total %></strong></div>
<% end %>

<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>
	    
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	
	      	<!--If there is an admin logged in. Admin only menu options-->
	      	<% if current_admin %>
						<li><%= link_to 'Products', products_path %></li>
						<li><%= link_to 'Users', users_path %></li>
						<li><%= link_to 'Categories', categories_path %></li>
						<li><%= link_to 'Checkouts', checkouts_path %></li>
						<li><%= link_to 'Logout', destroy_admin_session_path %></li>
	      	
	      	<!--Menu options for users & admins not logged in-->
	      	<% else %>
	      	
	       	<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Flowers & Gifts", products_path %></li>
			<li><%= link_to "About us", about_path %></li>
	        <li><%= link_to "Contact Us", contact_path %></li>

	      	
	      	<!--Link says 'login' if user hasn't, 'logout' if they have-->
	      	<!--Login/MyAccount button-->
	      	<li>
	      		<!--If user is logged in-->
	      		<% if current_user %>
	      		<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
	          
	          <ul class="dropdown-menu">
	            <li><%= link_to "Update Details", update_path%></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Order History", orderhistory_path%></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Logout",   destroy_user_session_path, method: :delete %></li>
	          </ul>
	        </li>
	        	
	        	<!--If user in not logged in-->
						<% else %>
    					<%= link_to 'Login', login_path %>
						<% end %></li>
						
						<!--Register button appears only if user is not logged in-->
						<li><% if current_user %><% else %>
						<%= link_to 'Register', register_path %>
						<% end %></li>
	        	
	        	
	        	<li><%= link_to "My Cart", cart_path %></li>

	       <%end%>
	       
	      </ul>
	      
	      <!--Get rid of search box
	      <form class="navbar-form navbar-right" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>-->
	        
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<!--Line below looks for the title variable in each .html.erb page and replaces the
	title variable here with it-->
  <title><%=yield(:title)%> | Fresh Flowers</title>
  <%= stylesheet_link_tag "application.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<!--Partial for header. Renders content from layouts/_header.html.erb-->
	<%=render'layouts/header'%>	
	
    	<!--The code below deals with flash messages and is necessary when using devise-->
    	<!--It also picks up all notices from pages and displays them uniformly.-->
	<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

	<%= yield %>

	<!--Partial for footer. Renders content from layouts/_footer.html.erb-->
	<%=render'layouts/footer'%>	
	
</body>
</html>